name: Aurionchat
version: ${version}
main: com.mineaurion.aurionchat.bukkit.PluginLoader
authors: [Yann151924]
website: https://mineaurion.com
depend:
  - LuckPerms
softdepend:
  - PlaceholderAPI
commands:
  chat:
    aliases: [ch, channel]
    description: "AurionChat's command to manage chat channels"
    usage: |
      /<command> - displays player current status on aurionchat
      /<command> join <channel> - join the specified channel and set as current one
      /<command> leave <channel> - leave the specified channel
      /<command> spy <channel> - spy/listen the channel speicified
      /<command> allListen - listen to all channels
      /<command> reload - reload the rabbitmq connection

permissions:
  aurionchat.chat.colors:
    default: false
    description: Righ to use color in chat
  aurionchat.chat.speak:
    default: false
    description: Right to speak in chat
  aurionchat.reload:
    default: false
    description: Reload connection

