name: Build
on:
  workflow_call:
    inputs:
      platform:
        required: true
        type: string
      branch:
        required: false
        default: master
        type: string
      version:
        required: false
        default: SNAPSHOT
        type: string
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.branch }}
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: corretto
          java-version: 17
      - name: Use gradle cache for faster builds
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-${{ matrix.platform }}-gradle-${{ hashFiles('**/*.gradle') }}
      - name: Cleanup Gradle Cache
        # Remove some files from the Gradle cache, so they aren't cached by GitHub Actions.
        # Restoring these files from a GitHub Actions cache might cause problems for future builds.
        run: |
          rm -f ~/.gradle/caches/modules-2/modules-2.lock
          rm -f ~/.gradle/caches/modules-2/gc.properties
      - name: Setup Gradle Wrapper Cache
        uses: actions/cache@v3
        with:
          path: ~/.gradle/wrapper
          key: ${{ runner.os }}-${{ matrix.platform }}-gradle-wrapper-${{ hashFiles('**/gradle/wrapper/gradle-wrapper.properties') }}
      - name: Forge don't like snapshot version
        if: ${{ inputs.platform=='forge' && inputs.version=='SNAPSHOT' }}
        run: |
          sed -i "s/pluginVersion=SNAPSHOT/pluginVersion=1/" gradle.properties
      - name: Change version
        if: ${{ inputs.version!='SNAPSHOT' }}
        run: |
          sed -i "s/pluginVersion=SNAPSHOT/pluginVersion=${{ inputs.version}}/" gradle.properties
      - name: Create release with Gradle
        run: ./gradlew ${{ inputs.platform }}:clean ${{ inputs.platform }}:build
      # TODO: workaround for fabric the -all version is not re-offuscated
      - name: Upload ${{ inputs.platform }}
        if: ${{ inputs.platform!='fabric' }}
        uses: actions/upload-artifact@v3
        with:
          name: ${{ github.event.repository.name }}-${{ inputs.version }}.jar
          path: ${{ inputs.platform }}/build/libs/*-all.jar
      - name: Upload ${{ inputs.platform }}
        if: ${{ inputs.platform=='fabric' }}
        uses: actions/upload-artifact@v3
        with:
          name: ${{ github.event.repository.name }}-${{ inputs.version }}.jar
          path: ${{ inputs.platform }}/build/libs/*-${{ inputs.version }}.jar